import archiver from 'archiver';

export async function buildSessionArchive({ participantId, sessionNumber, completionStatus, code, testsPassed, testsTotal }) {
  return new Promise((resolve, reject) => {
    const archive = archiver('zip', { zlib: { level: 9 } });
    const chunks = [];

    archive.on('warning', reject);
    archive.on('error', reject);
    archive.on('data', (chunk) => chunks.push(chunk));
    archive.on('end', () => resolve(Buffer.concat(chunks)));

    archive.append(code, { name: `session-${sessionNumber}/solution.py` });
    archive.append(JSON.stringify({
      participantId,
      sessionNumber,
      completionStatus,
      testsPassed,
      testsTotal,
      generatedAt: new Date().toISOString(),
    }, null, 2), { name: `session-${sessionNumber}/metadata.json` });
    archive.append('This archive was generated by the Appwrite study pipeline.', { name: `session-${sessionNumber}/README.txt` });

    archive.finalize().catch(reject);
  });
}
